Document: libssshydrax
Title: Debian libssshydrax Manual
Author: <insert document author here>
Abstract: This manual describes what libssshydrax is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libssshydrax/libssshydrax.sgml.gz

Format: postscript
Files: /usr/share/doc/libssshydrax/libssshydrax.ps.gz

Format: text
Files: /usr/share/doc/libssshydrax/libssshydrax.text.gz

Format: HTML
Index: /usr/share/doc/libssshydrax/html/index.html
Files: /usr/share/doc/libssshydrax/html/*.html
